### ISSUE TITLE
Cannot run program "git"

### ISSUE THREAD

**Issue by handschriftenportal-dev** [jenkinsci/conventional-commits-plugin#264]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.361.3
  OS: Linux - 4.19.0-23-amd64
  Java: 11.0.18 - Debian (OpenJDK 64-Bit Server VM)
  ---
  ace-editor:1.1
  active-directory:2.30
  analysis-model-api:10.23.1
  ansible:1.1
  antisamy-markup-formatter:159.v25b_c67cd35fb_
  apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
  authentication-tokens:1.4
  blueocean:1.26.0
  blueocean-autofavorite:1.2.5
  blueocean-bitbucket-pipeline:1.26.0
  blueocean-commons:1.26.0
  blueocean-config:1.26.0
  blueocean-core-js:1.26.0
  blueocean-dashboard:1.26.0
  blueocean-display-url:2.4.1
  blueocean-events:1.26.0
  blueocean-git-pipeline:1.26.0
  blueocean-github-pipeline:1.26.0
  blueocean-i18n:1.26.0
  blueocean-jira:1.26.0
  blueocean-jwt:1.26.0
  blueocean-personalization:1.26.0
  blueocean-pipeline-api-impl:1.26.0
  blueocean-pipeline-editor:1.26.0
  blueocean-pipeline-scm-api:1.26.0
  blueocean-rest:1.26.0
  blueocean-rest-impl:1.26.0
  blueocean-web:1.26.0
  bootstrap4-api:4.6.0-5
  bootstrap5-api:5.2.1-3
  bouncycastle-api:2.27
  branch-api:2.1071.v1a_188a_562481
  build-timeout:1.24
  caffeine-api:2.9.3-65.v6a_47d0f4d1fe
  checks-api:1.8.1
  cloudbees-bitbucket-branch-source:796.v6cb_1559e1673
  cloudbees-folder:6.758.vfd75d09eea_a_1
  cobertura:1.17
  code-coverage-api:3.5.0
  command-launcher:90.v669d7ccb_7c31
  commons-lang3-api:3.12.0-36.vd97de6465d5b_
  commons-text-api:1.10.0-36.vc008c8fcda_7b_
  config-file-provider:3.11.1
  conventional-commits:0.11.2
  credentials:1189.vf61b_a_5e2f62e
  credentials-binding:523.vd859a_4b_122e6
  dashboard-view:2.466.vdfefd95a_b_f8d
  data-tables-api:1.12.1-4
  dependency-check-jenkins-plugin:5.2.1
  display-url-api:2.3.7
  docker-commons:1.21
  docker-java-api:3.2.13-68.va_875df25a_b_45
  docker-plugin:1.3.0
  docker-workflow:563.vd5d2e5c4007f
  durable-task:504.vb10d1ae5ba2f
  echarts-api:5.4.0-1
  email-ext:2.92
  emailext-template:1.5
  embeddable-build-status:304.vdcf48d6b_d2eb
  envinject-api:1.199.v3ce31253ed13
  extended-choice-parameter:359.v35dcfdd0c20d
  extended-read-permission:3.2
  external-monitor-job:203.v683c09d993b_9
  favorite:2.4.1
  font-awesome-api:6.2.1-1
  forensics-api:1.17.0
  generic-tool:1.0
  git:4.14.3
  git-changelog:3.28
  git-client:3.13.1
  git-parameter:0.9.18
  git-server:99.va_0826a_b_cdfa_d
  github:1.36.1
  github-api:1.303-400.v35c2d8258028
  github-branch-source:1696.v3a_7603564d04
  gitlab-api:5.0.1-78.v47a_45b_9f78b_7
  gitlab-branch-source:646.vb_9560d64b_69f
  gitlab-oauth:1.16
  gitlab-plugin:1.6.0
  greenballs:1.15.1
  h2-api:1.4.199
  handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
  htmlpublisher:1.31
  http_request:1.16
  instance-identity:116.vf8f487400980
  ionicons-api:31.v4757b_6987003
  jackson2-api:2.14.2-319.v37853346a_229
  jacoco:3.3.2
  jakarta-activation-api:2.0.1-2
  jakarta-mail-api:2.0.1-2
  javadoc:226.v71211feb_e7e9
  javax-activation-api:1.2.0-5
  javax-mail-api:1.6.2-8
  jaxb:2.3.7-1
  jdk-tool:63.v62d2fd4b_4793
  jenkins-design-language:1.26.0
  jersey2-api:2.37-1
  jira:3.9
  jjwt-api:0.11.5-77.v646c772fddb_0
  jnr-posix-api:3.1.16-1
  job-dsl:1.81
  jquery:1.12.4-1
  jquery-detached:1.2.1
  jquery3-api:3.6.1-2
  jsch:0.1.55.61.va_e9ee26616e7
  junit:1166.1168.vd6b_8042a_06de
  kubernetes:3743.v1fa_4c724c3b_7
  kubernetes-client-api:6.4.1-208.vfe09a_9362c2c
  kubernetes-credentials:0.10.0
  ldap:659.v8ca_b_a_fe79fa_d
  lockable-resources:1069.v726298f53f8c
  m2release:0.16.3
  mailer:448.v5b_97805e3767
  matrix-auth:3.1.5
  matrix-project:785.v06b_7f47b_c631
  maven-plugin:3.21
  metrics:4.2.13-420.vea_2f17932dd6
  mina-sshd-api-common:2.9.2-50.va_0e1f42659a_a
  mina-sshd-api-core:2.9.2-50.va_0e1f42659a_a
  momentjs:1.1.1
  monitoring:1.92.0
  nodejs:1.5.1
  okhttp-api:4.9.3-108.v0feda04578cf
  pam-auth:1.10
  pipeline-build-step:486.vd08f550cceee
  pipeline-github-lib:38.v445716ea_edda_
  pipeline-graph-analysis:202.va_d268e64deb_3
  pipeline-groovy-lib:629.vb_5627b_ee2104
  pipeline-input-step:466.v6d0a_5df34f81
  pipeline-maven:1279.v5d711113020f
  pipeline-milestone-step:111.v449306f708b_7
  pipeline-model-api:2.2118.v31fd5b_9944b_5
  pipeline-model-definition:2.2118.v31fd5b_9944b_5
  pipeline-model-extensions:2.2118.v31fd5b_9944b_5
  pipeline-npm:0.9.2
  pipeline-rest-api:2.29
  pipeline-stage-step:305.ve96d0205c1c6
  pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
  pipeline-stage-view:2.29
  pipeline-utility-steps:2.15.0
  plain-credentials:143.v1b_df8b_d3b_e48
  plugin-util-api:2.20.0
  popper-api:1.16.1-3
  popper2-api:2.11.6-2
  prism-api:1.29.0-2
  pubsub-light:1.17
  pyenv-pipeline:2.1.2
  rebuild:1.34
  release:2.15
  resource-disposer:0.20
  role-strategy:587.v2872c41fa_e51
  run-condition:1.5
  scm-api:631.v9143df5b_e4a_a
  script-security:1229.v4880b_b_e905a_6
  shiningpanda:0.24
  snakeyaml-api:1.33-90.v80dcb_3814d35
  sonar:2.15
  sse-gateway:1.26
  ssh:2.6.1
  ssh-agent:327.v230ecd01f86f
  ssh-credentials:305.v8f4381501156
  ssh-slaves:2.854.v7fd446b_337c9
  sshd:3.270.vb_a_e71e64c287
  structs:324.va_f5d6774f3a_d
  test-results-analyzer:0.4.0
  timestamper:1.21
  token-macro:321.vd7cc1f2a_52c8
  trilead-api:2.84.v72119de229b_7
  variant:59.vf075fe829ccb
  warnings-ng:9.23.1
  workflow-aggregator:596.v8c21c963d92d
  workflow-api:1200.v8005c684b_a_c6
  workflow-basic-steps:994.vd57e3ca_46d24
  workflow-cps:3536.vb_8a_6628079d5
  workflow-durable-task-step:1217.v38306d8fa_b_5c
  workflow-job:1268.v6eb_e2ee1a_85a
  workflow-multibranch:716.vc692a_e52371b_
  workflow-scm-step:400.v6b_89a_1317c9a_
  workflow-step-api:639.v6eca_cd8c04a_a_
  workflow-support:839.v35e2736cfd5c
  ws-cleanup:0.43
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

### Reproduction steps

env.NEXT_VERSION = nextVersion(startTag: env.CURRENT_VERSION)

### Expected Results

should return a valid Version

### Actual Results

java.io.IOException: error=2, Datei oder Verzeichnis nicht gefunden
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at io.jenkins.plugins.conventionalcommits.process.ProcessUtil.execute(ProcessUtil.java:49)
	at io.jenkins.plugins.conventionalcommits.NextVersionStep$Execution.run(NextVersionStep.java:217)
	at io.jenkins.plugins.conventionalcommits.NextVersionStep$Execution.run(NextVersionStep.java:133)
	at org.jenkinsci.plugins.workflow.steps.SynchronousStepExecution.start(SynchronousStepExecution.java:37)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:322)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
Caused: java.io.IOException: Cannot run program "git" (in directory "/home/jenkins/jenkins_node/workspace/artung_nachweis_test_development"): error=2, Datei oder Verzeichnis nicht gefunden
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at io.jenkins.plugins.conventionalcommits.process.ProcessUtil.execute(ProcessUtil.java:49)
	at io.jenkins.plugins.conventionalcommits.NextVersionStep$Execution.run(NextVersionStep.java:217)
	at io.jenkins.plugins.conventionalcommits.NextVersionStep$Execution.run(NextVersionStep.java:133)
	at org.jenkinsci.plugins.workflow.steps.SynchronousStepExecution.start(SynchronousStepExecution.java:37)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:322)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at maven_build.call(maven_build.groovy:3)
	at pipeline_maven.call(pipeline_maven.groovy:38)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:90)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:116)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:85)
	at jdk.internal.reflect.GeneratedMethodAccessor359.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at jdk.internal.reflect.GeneratedMethodAccessor362.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:75)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:65)
	at jdk.internal.reflect.GeneratedMethodAccessor369.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:158)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:152)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:152)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:30)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:70)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Anything else?

- on cli as jenkins user i can execute git, PATH is looking ok(/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games)  
- in project Folder:  
  ```
  $ git --version
  git version 2.30.2
  ```
- .git folder is also existend

**Comment by gsomoza** [comment]
I have the same issue but I'm running Jenkins on Kubernetes (using the official Helm chart), using the official agent image as well. The agent does have Git: this error happens right after the repository is checked out into the working directory.

**Comment by gsomoza** [comment]
Looks like the right thing to do might be to switch to using jgit, see: https://github.com/jenkinsci/git-forensics-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/forensics/git/blame/GitBlamer.java

I'm not a Java programmer so unfortunately I can't contribute that kind of refactoring.

**Comment by handschriftenportal-dev** [comment]
Thanks for response, i enabled jgit in Jenkins but had no effect on the build.

**Comment by wanghu001** [comment]
I am having same issue, even though I have git installed in my environment
