### ISSUE TITLE
nextVersion: Unexpected character

### ISSUE THREAD

**Issue by kobmik** [jenkinsci/conventional-commits-plugin#293]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

We would like to use nextVersion() in a Jenkins pipeline to generate the next semantic version.
The plugin can read the current tag but fails to generate the next version.

### Expected Results

return the next version

### Actual Results

Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 9c419606-6cbd-430f-ae09-f66bb71a5bf2
Unexpected character 'ILLEGAL([)' at position '0', expecting '[DIGIT]'
	at com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516)
	at com.github.zafarkhaja.semver.VersionParser.digits(VersionParser.java:448)
	at com.github.zafarkhaja.semver.VersionParser.numericIdentifier(VersionParser.java:408)
	at com.github.zafarkhaja.semver.VersionParser.parseVersionCore(VersionParser.java:285)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:255)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
	at com.github.zafarkhaja.semver.Version.valueOf(Version.java:265)
...

**Comment by hepifish** [comment]
same here..

**Comment by anvi-27** [comment]
The gitag accepted seems to be only of type digits; the git tag must be in the format of only number with no prefix.
Accepted: 1.0.0
Not accepted: v1.0.0, [1.0.0]

**Comment by salmonito** [comment]
Whish this is explained in docs. But anyway project does not seem to be supported.

**Comment by philippart-s** [comment]
Hi @salmonito, effectively I'm alone on this plugin and I have no time to maintain it.
If you will help by adding more details in the documentation it will be very convenient for me ;)
